version: '3.1'
services:
  db:
    image: bpederencino/devops-labs-mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  api:
    image: api
